### ISSUE TITLE
compile failed with gcc-6.1

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-material#157]
I tried to test a newer gcc compiler, the other opm modules compile very smoothly, especially for opm-simulators, but opm-material meet one issue.

```
In file included from /home/liuming/work/opm/opm-material/tests/test_fluidsystems.cpp:31:0:
/home/liuming/work/opm/opm-material/opm/material/checkFluidSystem.hpp: In function ‘void checkFluidSystem() [with Scalar = double; FluidSystem = Opm::FluidSystems::SinglePhase<double, Opm::GasPhase<double, Opm::N2<double> > >; RhsEval = Opm::DenseAd::Evaluation<double, 3>; LhsEval = Opm::DenseAd::Evaluation<double, 3>]’:
/home/liuming/work/opm/opm-material/opm/material/checkFluidSystem.hpp:367:100: internal compiler error: in assign_temp, at function.c:961
             try { auto tmpVal = FluidSystem::diffusionCoefficient(fs, paramCache, phaseIdx, compIdx); static_assert(std::is_same<decltype(tmpVal), RhsEval>::value, "The default return value must be the scalar used by the fluid state!"); } catch (...) {};
                                                                                                    ^
0x885945 assign_temp(tree_node*, int, int)
	../../src/gcc/function.c:961
0x75cbc7 expand_call(tree_node*, rtx_def*, int)
	../../src/gcc/calls.c:2569
0x83d6f6 expand_expr_real_1(tree_node*, rtx_def*, machine_mode, expand_modifier, rtx_def**, bool)
	../../src/gcc/expr.c:10594
0x768b08 expand_expr
	../../src/gcc/expr.h:256
0x768b08 expand_call_stmt
	../../src/gcc/cfgexpand.c:2660
0x768b08 expand_gimple_stmt_1
	../../src/gcc/cfgexpand.c:3548
0x768b08 expand_gimple_stmt
	../../src/gcc/cfgexpand.c:3714
0x769c45 expand_gimple_basic_block
	../../src/gcc/cfgexpand.c:5720
0x76eb26 execute
	../../src/gcc/cfgexpand.c:6335
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/test_fluidsystems.dir/tests/test_fluidsystems.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_fluidsystems.dir/all] Error 2
make: *** [all] Error 2


```

**Comment by alfbr** [comment]
I have not investigated the specific output above, but please be aware the GCC has seen breakage of C++ ABI on recent releases. This has resulted in linking problems between system compiled Boost and OPM. For instance, I believe building OPM on Debian stable with GCC 6 fails, while building OPM on Debian testing with GCC 6 was done successfully some weeks ago.

**Comment by jokva** [comment]
This error is way before linking.
________________________________
Fra: Alf Birger Rustad [notifications@github.com]
Sendt: 11. juli 2016 08:54
Til: OPM/opm-material
Emne: Re: [OPM/opm-material] compile failed with gcc-6.1 (#157)


I have not investigated the specific output above, but please be aware the GCC has seen breakage of C++ ABI on recent releases. This has resulted in linking problems between system compiled Boost and OPM. For instance, I believe building OPM on Debian stable with GCC 6 fails, while building OPM on Debian testing with GCC 6 was done successfully some weeks ago.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/OPM/opm-material/issues/157#issuecomment-231655341>, or mute the thread<https://github.com/notifications/unsubscribe/AIRDNV6r33DbO65pmj3-a_jsvWaNm_H-ks5qUeiMgaJpZM4JI-Wl>.


-------------------------------------------------------------------
The information contained in this message may be CONFIDENTIAL and is
intended for the addressee only. Any unauthorised use, dissemination of the
information or copying of this message is prohibited. If you are not the
addressee, please notify the sender immediately by return e-mail and delete
this message.
Thank you

**Comment by alfbr** [comment]
> This error is way before linking.

Yes, but I am not sure that rules out ABI related issues. From the short text above it looks like a GCC bug, and if so, it should be reported. Still, I think it makes sense to check compilation using a new GCC tool-chain throughout before concluding.

**Comment by jokva** [comment]
It has nothing to do with the ABI.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71210

Seems like it has been reported and fixed.

**Comment by alfbr** [comment]
Indeed, it looks like the same bug, thanks for digging it up.

**Comment by andlaus** [comment]
according to @joakim-hove all GCCs before 4.8 were hit by a bus a while ago when it comes to OPM (cf. OPM/opm-parser#608). I assume that this still holds? (if no, I don't mind testing my stuff on older compilers too, but "oldest supported compiler" needs to be clearly defined.)

**Comment by jokva** [comment]
That still holds, i.e. there is no requirement for the code to work on gcc <4.8. This is 6.1 though and obviously after 4.8, but is a (fixed?) compiler bug.

**Comment by alfbr** [comment]
Not sure I see the relevance, we are discussing what looks like a bug in GCC 6.1, it is the latest and greatest. @qilicun will need to share what other compiler versions were involved in the tool-chain. With the bug report @jokva dug up, I suggest testing with a development version of GCC or waiting until such a version is easily available.

**Comment by andlaus** [comment]
oh, sorry: I read 4.6...

**Comment by qilicun** [comment]
>Where did you get 6.1? Compile from source?

From a ubuntu ppa  https://launchpad.net/~ubuntu-toolchain-r

>I suggest testing with a development version of GCC or waiting until such a version is easily available.

I need to say that this is the only issue when I compile all the opm modules with gcc-6
Following is the compiler version information.

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.1.1-3ubuntu11~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.1.1 20160511 (Ubuntu 6.1.1-3ubuntu11~14.04.1) 

```

**Comment by jokva** [comment]
This problem will probably go away with compiler upgrades. Reopen if it keeps happening.

**Comment by alfbr** [comment]
> From a ubuntu ppa https://launchpad.net/~ubuntu-toolchain-r

It seems GCC 6 was updated at May 10 in the ppa, while the bug report suggest the fix was done May 20. If you want to confirm the fix, you will need to wait until they update, or find an up-to-date GCC elsewhere.

> ubuntu11~14.04.1

It seems you are using Ubuntu 14.04, which means you are mixing tool chains. While this may be unrelated to the issue here, you should be aware that there is ABI breakage which may cause strange errors. If you want to test bleeding edge GCC, I suggest doing it on a platform built with GCC 5.1 or newer. For Ubuntu that means 15.10 or 16.04.

> I need to say that this is the only issue when I compile all the opm modules with gcc-6
Following is the compiler version information.

Still, this seems to be a compiler bug. Making workarounds in our code for compiler bugs that are already fixed, and not shipped with any distributions, seems like a slippery slope to me.

**Comment by qilicun** [comment]
@alfbr 
Thanks for the details!

**Comment by andlaus** [comment]
ok, I can now confirm that this seems to be a temporary hiccup with your GCC: I compiled an ran flow with the latest GCC svn version and everything seems to work fine for Norne and SPE9. (the compiler produced *a lot* of warnings within Eigen, though.)

**Comment by jokva** [comment]
Splendid, thanks for checking.
