### ISSUE TITLE
results degradation with JFUNC

### ISSUE THREAD

**Issue by totto82** [OPM/opm-material#199]
When I compare current results for Model 2.2 with results from end of 2016 there is a significant change of results. If I comment out JFUNC the results stays the same. I guess something wrong happened when the new JFUNC implementation in opm-parser was introduced. 
@andlaus, @jokva Any idea?

**Comment by pgdr** [comment]
That's interesting since the parser doesn't do anything but internalize the keyword.  The implementation and (reverting of) SI conversion is still done in material.

**Comment by pgdr** [comment]
Okey, I don't have Model 2.2, so I can't test it right now.  Will try to acquire it and come back to you.

**Comment by andlaus** [comment]
@pgdr: we've found the issue(s): the internalized JFUNC object provides the surface tension via non SI-units (i.e., dyn/cm instead of N/m) and the pressure column of the satfunc tables now does not converted into pressure anymore if JFUNC is present. the latter causes the manual conversion of the "pressure" column to the jfunc in opm-material to be invalid. @totto82 and me fixed this, but we need a bit of time to test the fix. (also, were these changes intended by OPM/opm-parser#956?)

**Comment by pgdr** [comment]
Perhaps you, for transparency, can make a _WIP-PR_ while you test?

**Comment by andlaus** [comment]
the patches are currently only on @totto82's computer.

besides correctness, the question is whether you'd like this to be done completely in opm-material, completely in opm-parser or partially in both.

**Comment by pgdr** [comment]
We've been through this before, and I would of course have it all in the _parser_ since it is part of the parsing.

I just want to mention that I find it surprising and slightly discomforting that no tests caught this.

**Comment by andlaus** [comment]
> We've been through this before, and I would of course have it all in the parser since it is part of the parsing.

ok, as you like. as I see it the wrong unit of the surface tension should go to parser, while the unit conversion of the pressure columns is a matter of preference.

**Comment by atgeirr** [comment]
I assume this can be closed now. Can you confirm, @totto82?
