### ISSUE TITLE
call opm-material from dumux

### ISSUE THREAD

**Issue by berndflemisch** [OPM/opm-material#200]
As discussed with some OPM developers, we would like to evaluate the feasibility of using opm-material in Dumux.

I made a first attempt and converted the Dumux test_box2p2c. The OPM changes are documented in the branch `feature/call-from-dumux`. Note that this is against the release 2016.04, I hope that not too much did change there. The Dumux changes are documented here:
https://git.iws.uni-stuttgart.de/dumux-repositories/dumux/merge_requests/366

Encountered issues:

1. Opm's Valgrind.hh and Dumux' valgrind.hh define the same functions in the same namespace. They differ in the way `HAVE_VALGRIND` is treated. It isn't possible to use both at the same time. The one from OPM is nicer. A possibility would be to use that one also in Dumux and put a `namespace Dumux` around the `namespace Valgrind`. For the moment, I just commented the inclusions of the Opm file.

2. Dumux' 2p2c model expects the FluidSystem to export indices `{w,n}PhaseIdx` and `{w,n}CompIdx`. One solution would be to add them to Opm's FluidSystem.

3. The `NullParameterCache` is a template class in Opm and a non-template class in Dumux. I solved it by using Opm's one in the VolumeVariables. A better solution is needed to make have the possibility to switch between using dumux/material and opm-material.

4. The FluidSystems have a different interface for the (binary) diffusion coefficient, the FluidMatrixInteractions have different interfaces for the capillary pressure and relperms. Again, I solved it by using Opm's one in the VolumeVariables. This could be made flexible (but not nice) by SFINAE and `std::enable_if`. Or interface unification.

5. The MaterialLawParameters have different interfaces. Since the call are on the top level, it is a minor thing.

6. The ConstraintSolver types are hardcoded in the VolumeVariables. This could be solved by creating properties such that they can be changed on the top level.

7. Opm's FluidState doesn't offer a function setMassFraction which seems to be convenient when mass instead of the mole fractions are usedas primary variables. Naturally, I would have nothing against adding this to Opm's FluidStates.

8. The results are not dramatically, but quite a bit different. This needs to be investigated.

Comments are welcome!

**Comment by andlaus** [comment]
wow, that was quick :+1:

some explanations to your remarks:

to 1) we could make Valgrind:: a sub-namespace of Opm:: or you could move your version into Dumux:: (or both). Please indicate your preference.
to 2) the phase and component names have intentionally not been standardized because generic models are not supposed to need them. what are they needed for in the 2p2c model?
to 3) the problem with the parameter caches is AD: the scalar type of the which quantities that shall be cached may vary, so the ParamCache object needs to know it. That said, isn't the parameter cache a transient object that vanished at the end of the `VolumeVariables::update()` method?
to 4) I have to confess that molecular diffusion is not part of my comfort zone, i.e., better solutions are highly appreciated.
to 6) opm-material should have all constraint solvers required by the `2p2c` model and they should only need a fluid state object. maybe these could be used?
to 7) IIRC the problem was that to implement this function for fluid states which store mole fractions, the mole fractions of the other components are needed. (this was slightly inefficient and caused some trouble but I don't really remember what.) An alternative would be to store mass fractions from the outset, but then the same problems would arise for a `setMoleFraction()` method. ideas/patches welcome.

I've also looked at your changes and have some remarks of my own:

- it is better to use `MaterialLaw::capillaryPressure(pcArray, params, fluidState)` instead of the low level methods directly. the capillary pressure between phase alpha and beta then is defined as `pcArray[beta] - pcArray[alpha]` and the pressure for phase beta is thus `p[beta] = p[alpha] + pcArray[beta] - pcArray[alpha]`.
- the relperms are IMO better computed using `relativePermeabilities()`, i.e. for all phases at once.
- to me it looks like the Kelvin effect can be implemented by making the fugacity coefficient of the fluid system pressure dependent, i.e., the model should not need to care about it. I may miss something here, though.
- If you would like to avoid hardcoding the parameter class for the material law (`BCTraits`), have a look at the `Opm::TwoPhaseMaterialTraits` template class which is defined in the `opm/material/fluidmatrixinteractions/MaterialTraits.hpp` header. (you can also use the enums provided by the fluid system at this point.)

**Comment by atgeirr** [comment]
> we could make Valgrind:: a sub-namespace of Opm::

I think that should be done in any case.

> the problem with the parameter caches is AD: the scalar type of the which quantities that shall be cached may vary, so the ParamCache object needs to know it.

But a null cache should not really need it, so for flexibility of use we could let the `Evaluation` template parameter have a default (a null type)? 

> The FluidSystems have a different interface for the (binary) diffusion coefficient, the FluidMatrixInteractions have different interfaces for the capillary pressure and relperms. Again, I solved it by using Opm's one in the VolumeVariables. This could be made flexible (but not nice) by SFINAE and std::enable_if. Or interface unification.

Interface unification would be preferable, at least for capillary pressure and relperms (which should be in the intersection of our comfort zones...). @andlaus what would be needed here?

**Comment by andlaus** [comment]
> But a null cache should not really need it, so for flexibility of use we could let the Evaluation template parameter have a default (a null type)?

in principle, the NullParameterCache objects are not needed in the first place, because they contain -- well -- no data ;)

the whole point of that template is to provide a type which adheres to the same API as non-trivial parameter objects so that the calling code for both scenarios can be identical. for this I cannot really see a way around supplying a template parameter. (also, defaulting that template argument instead of having to specify it explicitly may lead to unintuitive compiler errors.)

> @andlaus what would be needed here?

As far as I can see, the only thing that would be required for opm-material are some renames, since the fluid-matrixinteractions API of opm-material is basically a superset of the dumux one. That said, since a patch for the Dumux models is required anyway, it would IMO be smarter to use the phase-independent way to calculate the capillary pressures and relperms in dumux.

**Comment by berndflemisch** [comment]
Thank you for moving the Valgrind stuff into the Opm namespace. I will try to move everything to the master as soon as possible. I would like to enter an interface discussion only after we have created a strong case for using opm-material from Dumux. Which is when we can use AD for one Dumux model.

**Comment by atgeirr** [comment]
> Thank you for moving the Valgrind stuff into the Opm namespace. I will try to move everything to the master as soon as possible. I would like to enter an interface discussion only after we have created a strong case for using opm-material from Dumux. Which is when we can use AD for one Dumux model.

Sounds good. Is there anything else you'd like from us at this point?

**Comment by andlaus** [comment]
> it would IMO be smarter to use the phase-independent way to calculate the capillary pressures and relperms in dumux.

I've just checked: That functionality is also present in the Dumux material law framework -- The M-phase N-component model does it that way.

I suppose that this means that the dumux models can be modified  to use this without modifying its current material laws.

**Comment by andlaus** [comment]
can I close this?

**Comment by andlaus** [comment]
since silence is golden, I suppose that this can be closed ;)
