### ISSUE TITLE
Some shared_ptr in EclMaterialLawManager are of little use

### ISSUE THREAD

**Issue by blattms** [OPM/opm-material#67]
In the current master both `EclMaterialLawManager::oilWaterEpsInfoDrainage_` is a vector of `shared_ptr`, but according to the code that initializes its entries each shared_ptr is actually created as a new pointer. Thus there will be now duplicates. (I assume that the original designe idea was to point to the entries of `unscaledEpsInfo_` if there are no element specific parameters.)

For  `EclMaterialLawManager::materialLawParams` the picture is slightly different. If `hasElementSpecificParameters()` is false, then the entries point to the parameters for the satnumRegions the element belongs to. I am not sure what the more often use case is: element specific parameters or not.

We should ask us whether the memory savings in some cases outweight the additional level of indirection and code obfuscation. To the very least it makes communicating the values harder.

**Comment by andlaus** [comment]
> In the current master both EclMaterialLawManager::oilWaterEpsInfoDrainage_ is a vector of shared_ptr, but according to the code that initializes its entries each shared_ptr is actually created as a new pointer. Thus there will be now duplicates. 

the point with that is that if hysteresis is disabled, everything can point to the same (dummy) object and the per-element parameter objects only need to get larger by `sizeof(size_t)` in that case.

> We should ask us whether the memory savings in some cases outweight the additional level of indirection and code obfuscation. To the very least it makes communicating the values harder.

because these objects are always accessed using the respective accessor methods, this difference only affects the initialization code. (and I suppose the init code will not become much simpler if the full hysteresis parameter objects are copied into the threephase parameter objects instead of having just pointing.)

**Comment by andlaus** [comment]
that issue has been resolved I suppose (material parameters are now always element specific)? If I misinterpreted something, feel free to re-open.
