### ISSUE TITLE
Wrong maxPcow and maxPcgo

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-material#99]
When I use "EclEpsScalingPoints.hpp" to output all the endpoints value in saturation tables, I get the wrong number for maxPcow and maxPcgo when the capillary pressure is not zero. I test some cases like spe1, spe3, and spe9, but it does not get the correct value in all of these cases. But I checked the code, it looks correct in the implementation. maybe something wrong in the parser? I'm not sure.

**Comment by andlaus** [comment]
does the deck you're looking at feature the `SWATINIT` keyword? That one causes the maximum capillary pressure to be modified...

**Comment by qilicun** [comment]
Sorry, missing the unit changes.

**Comment by andlaus** [comment]
no problem. I thought a bit about it, and I think it might be easier for you if you do the consistency checks at the end of the `extract*()` methods of the `EclEpsScalingPointsInfo` class:

https://github.com/OPM/opm-material/blob/master/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp#L122

 (because there you have more explicit names than in `EclEpsScalingPoints` for the values you'd like to check.) Are you aware of this class?

**Comment by qilicun** [comment]
> Are you aware of this class?

Yes, I'm using this class for relperm diagnostics.
